---
title: "Retirement Plan Calculator - Proposal"
author: "Angela Sofia Burkhart Colorado"
output:
  pdf_document:
        latex_engine: xelatex
---

## Description 

This calculator will be created to make retirement information more accessible to non-English speakers. 

## Workflow 

<table>
User Inputs                   Outputs
--------------                -----------
Annual Income                 Future Savings
Bi-weekly contribution        Total Number of Deposits 
Years to retirement           Total Contribution by Employee
Annual Interest Rate (APR%)    
</table>

Compounded interest will be calculated over specified number of years till retirement at the specified APR. 

## Calculations 

1. Percentage of income being contributed annually 
2. Contribution of from company (max 4% of annual income)
3. Future Savings 
4. Total Deposits 
    + how many deposits were made in the years till retirement 
    + how much money was contributed 
    
### *1. Percentage of Income Being Contributed Annually* 

$${Total  Annual Contribution}= 24 * Biweekly Contribution $$
$$PercentageOfSalary = {Total Annual Contribution \over Salary}*100$$

### *2. Contribution by Company* 

$$MaxCompanyContribution = 0.04*Salary$$
$$Company Contribution = PercentageOfSalary*Salary$$
where 

$$0 < Salary \leq MaxCompanyContribution$$

### *3. Future Savings* 

We assume there are 52 weeks in a year (this can be off by a day or two). Hence bi-weekly contributions would mean there are 26 contributions a year. 

$$TotalNumberOfContributions = YearsTillRetirement * 26$$

$$FV = PV * (1 + i)^n$$

+ FV: future value 
+ PV: present value (first deposit + employer contribution)
+ i: rate of interest earned (APR)
+ n: number of periods (*TotalNumberOfContributions* - 1 )

### *4. Total Deposits* 

$$TotalNumberOfContributions$$

$$Total Contribution = Total Annual Contribution * Years Till Retirement$$